version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm run install:lambda
      - npm update
  build:
    commands:
      - npm run deploy:cicd
  post_build:
    commands:
      - npm run test:remote
